apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: smart-grocery

resources:
  - namespace.yaml
  - configmap.yaml
  - redis-pv.yaml
  - redis-deployment.yaml
  - server-deployment.yaml
  - client-deployment.yaml
  - ingress.yaml
  - hpa.yaml

commonLabels:
  app.kubernetes.io/name: smart-grocery
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize
